<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-888A2JB" name="Keywords.TimeoutsPractice" tests="3" failures="0" timestamp="2022-08-03T08:34:46 IST" time="5.050" errors="1">
  <testcase name="notificationpageTest" time="0.005" classname="Keywords.TimeoutsPractice"/>
  <testcase name="notificationpageTest" time="0.005" classname="Keywords.TimeoutsPractice"/>
  <testcase name="homepageTest" time="5.040" classname="Keywords.TimeoutsPractice">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method Keywords.TimeoutsPractice.homepageTest() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Keywords.TimeoutsPractice.homepageTest() didn't finish within the time-out 5000
at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- homepageTest -->
</testsuite> <!-- Keywords.TimeoutsPractice -->
